Group all difficulties of glitchless, group macros and item requirements
lepelog/sslib pull request #88
Opened 2021-05-11 17:27 UTC by yannl35133

I managed to put everything together, and it doesn't crash (on the first 100 seeds at least).
I haven't tested the soundness of the seeds.

Also, I based the commit off of gui-redesign, but creating another branch may be better

2021-05-19 14:47 UTC, lepelog requested changes
Looks good. I guess `SS Rando Logic - Item Location.yaml` and `SS Rando Logic - Macros.yaml` can be deleted, no need to keep them around since they are replaced with new files.
I've brought this up before and came to the conclusion, that "glitchless logic" and glitched logic should be 2 separate files

2021-05-19 14:47 UTC, lepelog commented on asm/patch_diffs/custom_funcs_diff.txt
> +      0x68]
Please revert the merge of the fix-bit-crashes branch, that merge should be done separately and also will need an ui option as well

2021-05-19 14:47 UTC, lepelog commented on asm/patches/ss_necessary.asm
> +; this patch branches to the custom trigger_exit_one function, when a scenechange is needed to outside of sky keep
If you're already fixing those, make them all uppercase

2021-05-19 14:47 UTC, lepelog commented on patches.yaml
> -  - name: Clawshot Target for 2nd small Key
I feel like "Clawshot Target" can stay as it is?

2021-05-19 14:47 UTC, lepelog commented on ssrando
> +#!/bin/sh
This was probably committed by accident, remove

2021-05-20 01:04 UTC, yannl35133 commented on asm/patches/ss_necessary.asm
> +; this patch branches to the custom trigger_exit_one function, when a scenechange is needed to outside of sky keep
The space is the most important part, and there's no capital letters here, should I really ?

2021-05-20 01:10 UTC, closed without merging