New logic
lepelog/sslib pull request #92
Opened 2021-05-20 01:20 UTC by yannl35133

Messed up with my repository, I'm not very good with git yet

2021-05-22 15:30 UTC, lepelog requested changes
Looks good, just a few things

Also split the logic into glitchless and glitched logic, I'll review the logic files after that. Since the tricks for glitched and glitched should be entirely separate imo (and glitched logic should behave as having all glitchless tricks enabled), they should also be separate on the UI, although that would be a job for @cjs8487

2021-05-22 15:30 UTC, lepelog commented on hints.yaml
> +Thunderhead - Gossip Stone on Bug Rock:
```suggestion
Thunderhead - Gossip Stone near Bug Heaven:
```
It's actually not on the island, also I prefer Bug Heaven over Bug Rock

2021-05-22 15:30 UTC, lepelog commented on hints.yaml
> +  Need: Can Access Front of Temple of Time & Hook Beetle
This does not need Hook Beetle with the precise slingshot shot and also for glitched logic you can get there with beating the dungeon inside LMF

2021-05-22 15:30 UTC, lepelog commented on logic/hints.py
> +    'Knight Academy - Pumpkin Pull - 600 Points',
I think this should stay as Pumpkin Archery

2021-05-22 15:30 UTC, lepelog commented on logic/hints.py
> +    "Sky - Dodoh's High Dive - 500 Rupees",
I think Fun Fun Island Minigame can stay as it is

2021-05-22 15:30 UTC, lepelog commented on logic/hints.py
> +    'Thunderhead - Bug Heaven - 10 Bugs in 3 Minutes',
Change that back as well

2021-05-22 15:30 UTC, lepelog commented on randomizer-changes.md
> +- A clawshots target was added near the first trapped mogma chest. This is so you can escape from the corner without dying without gust bellows
clawshot target

2021-05-22 20:53 UTC, yannl35133 commented on hints.yaml
> +  Need: Can Access Front of Temple of Time & Hook Beetle
Those were unused

2021-05-22 21:01 UTC, yannl35133 commented
What would be the benefits of a split between Glitched and Glitchless, apart from code duplication ?

What should the basis of check names be ? I considered official names as a pretty solid one.

I also consider that including score requirements in minigame checks (that allow it) is a good idea. I forgot to add the requirement of Rickety Coaster, I'll add it.

Should I solve the conflicts with the current gui-redesign ?

2021-05-24 23:00 UTC, lepelog commented
For check names, it just really matters that it's recognizable. Like, if you have to think "is this the right check", then the name is probably bad. Imo it's not in the scope of this PR to fix check names, I already gave feedback to some I want to be changed back and the rest I don't really mind. Fixing typos in check names is fine. I don't really know how to properly coordinate check name changes (since there are a lot of names we always wanted to change), probably in discord somehow. After this is merged, you are also welcome to submit a PR with name changes.

Not sure if having the required points/time in the check name is a good idea, but as I said above, it's out of scope and should be discussed in discord. Generally I prefer shorter check names, cause they fit on in game textboxes more easily, but cj is working on removing that restriction so it's something that we can think about.

Yes, please resolve the conflict

2021-05-26 22:02 UTC, yannl35133 commented
Conflict resolved, name changes reverted (I'll make another PR)

2021-05-31 14:42 UTC, lepelog commented
The only thing holding me back from merging this is that glitched and glitchless tricks are not separated. I refuse to merge this when glitchless tricks can be disabled with BiT active, we already agreed on that glitched logic should have all glitched tricks implicitly enabled. I'm fine with merging the one file solution now until I have time to refactor it.

2021-05-31 14:44 UTC, yannl35133 commented
I don't entirely agree, I don't see why it is necessary, but I won't oppose it (as fiercely as the one file requirements)

2021-06-09 15:31 UTC, merged